import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useProfiles } from '@/hooks/useProfiles';
import { fetchTitleRating, fetchWatchlistStatus, rateTitle, unrateTitle, addToWatchlist, removeFromWatchlist, fetchMyRatings, fetchMyWatchlist, type TitleSnapshot } from '@/lib/userApi';

const effective = (explicit:string|null|undefined, activeId:string|null|undefined) => explicit ?? activeId ?? 'default';

export function useTitleRating(mediaType:string,titleId:number,profileId?:string|null){const{activeId}=useProfiles();const pid=effective(profileId,activeId);return useQuery({queryKey:['rating',mediaType,titleId,pid],queryFn:()=>fetchTitleRating(mediaType,titleId,pid),staleTime:60_000});}
export function useRateMutation(mediaType:'movie'|'tv',titleId:number,profileId?:string|null){const{activeId}=useProfiles();const pid=effective(profileId,activeId);const qc=useQueryClient();return useMutation({mutationFn:({rating,snapshot}:{rating:number;snapshot:TitleSnapshot})=>rateTitle(titleId,mediaType,rating,snapshot,pid),onSuccess:()=>{qc.invalidateQueries({queryKey:['rating',mediaType,titleId,pid]});qc.invalidateQueries({queryKey:['myRatings',pid]});}});}
export function useUnrateMutation(mediaType:string,titleId:number,profileId?:string|null){const{activeId}=useProfiles();const pid=effective(profileId,activeId);const qc=useQueryClient();return useMutation({mutationFn:()=>unrateTitle(mediaType,titleId,pid),onSuccess:()=>{qc.invalidateQueries({queryKey:['rating',mediaType,titleId,pid]});qc.invalidateQueries({queryKey:['myRatings',pid]});}});}
export function useWatchlistStatus(mediaType:string,titleId:number,profileId?:string|null){const{activeId}=useProfiles();const pid=effective(profileId,activeId);return useQuery({queryKey:['watchlist',mediaType,titleId,pid],queryFn:()=>fetchWatchlistStatus(mediaType,titleId,pid),staleTime:60_000,enabled:!!pid});}
export function useWatchlistMutation(mediaType:'movie'|'tv',titleId:number,profileId?:string|null){const{activeId}=useProfiles();const pid=effective(profileId,activeId);const qc=useQueryClient();return useMutation({mutationFn:({snapshot}:{snapshot:TitleSnapshot})=>addToWatchlist(titleId,mediaType,snapshot,pid),onSuccess:()=>{qc.invalidateQueries({queryKey:['watchlist',mediaType,titleId,pid]});qc.invalidateQueries({queryKey:['myWatchlist',pid]});}});}
export function useUnwatchlistMutation(mediaType:string,titleId:number,profileId?:string|null){const{activeId}=useProfiles();const pid=effective(profileId,activeId);const qc=useQueryClient();return useMutation({mutationFn:()=>removeFromWatchlist(mediaType,titleId,pid),onSuccess:()=>{qc.invalidateQueries({queryKey:['watchlist',mediaType,titleId,pid]});qc.invalidateQueries({queryKey:['myWatchlist',pid]});}});}
export function useMyRatings(profileId?:string|null){const{activeId}=useProfiles();const pid=effective(profileId,activeId);return useQuery({queryKey:['myRatings',pid],queryFn:()=>fetchMyRatings(pid),enabled:!!pid});}
export function useMyWatchlist(profileId?:string|null){const{activeId}=useProfiles();const pid=effective(profileId,activeId);return useQuery({queryKey:['myWatchlist',pid],queryFn:()=>fetchMyWatchlist(pid),enabled:!!pid});}
