// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/bingr-states/ErrorCompact.tsx": () => import("../components/mockups/bingr-states/ErrorCompact.tsx"),
  "./components/mockups/bingr-states/ErrorFull.tsx": () => import("../components/mockups/bingr-states/ErrorFull.tsx"),
  "./components/mockups/bingr-states/SkeletonDetail.tsx": () => import("../components/mockups/bingr-states/SkeletonDetail.tsx")
};
