import { useEffect, useRef, useState } from 'react';
import { useParams } from 'wouter';
import { Download, Loader2, X } from 'lucide-react';
import BingrWatch from './BingrWatch';
import { getAccessToken } from '@/lib/supabase';
import { useContinueWatching } from '@/hooks/useContinueWatching';

type DownloadOption={server?:string;url?:string;quality?:number|string;size?:string;source?:string};
type DownloadResponse={ok?:boolean;title?:string;downloads?:DownloadOption[]};
function qualityLabel(v:DownloadOption['quality']){const n=Number(v);if(n===2160)return'4K';if([1080,720,480,360,240].includes(n))return`${n}p`;return'HD'}
function openDownload(url:string){if(!url)return;const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.style.display='none';document.body.appendChild(a);a.click();a.remove()}
function progressKey(mediaType:string,id:number,s?:number,e?:number){return`rabbitrip:progress:${mediaType}:${id}:${s??'movie'}:${e??'movie'}`}
function headers(){const t=getAccessToken();return t?{Authorization:`Bearer ${t}`}:{}}
function RecoveryAndProgress({mediaType,id,season,episode,title}:{mediaType:'movie'|'tv';id:number;season?:number;episode?:number;title?:string}){
 const {addOrUpdate,markCompleted}=useContinueWatching();const resumeRef=useRef(0);const wantedPlayRef=useRef(false);const videoRef=useRef<HTMLVideoElement|null>(null);const lastSave=useRef(0);
 useEffect(()=>{let cancelled=false;let timer:ReturnType<typeof setInterval>|null=null;const local=progressKey(mediaType,id,season,episode);const getVideo=()=>{const v=document.querySelector('video');return v instanceof HTMLVideoElement?v:null};
 const restore=async(v:HTMLVideoElement)=>{const token=getAccessToken();let position=0;let duration=Number(v.duration||0);try{const raw=localStorage.getItem(local);if(raw){const p=JSON.parse(raw);position=Number(p.position_seconds||0);duration=duration||Number(p.duration_seconds||0)}}catch{}if(token){try{const q=new URLSearchParams({mediaType,id:String(id),profileId:(localStorage.getItem('rabbitrip.activeProfile:'+((JSON.parse(localStorage.getItem('rabbitrip.supabase.session')||'{}')?.user?.id)||'guest'))||'default'),id:String(id)});if(season!==undefined)q.set('season',String(season));if(episode!==undefined)q.set('episode',String(episode));const r=await fetch(`/api/progress?${q}`,{headers:headers()});if(r.ok){const d=await r.json();if(d.progress){const remote=Number(d.progress.position_seconds||0);if(remote>position){position=remote;duration=duration||Number(d.progress.duration_seconds||0)}}}}catch{}}
 if(position>3&&duration>0){const safe=Math.min(position,Math.max(0,duration-1));try{v.currentTime=safe}catch{}}};
 const save=async(completed=false)=>{const v=videoRef.current;if(!v||cancelled)return;const position=Number(v.currentTime||0),duration=Number(v.duration||0);if(!Number.isFinite(position)||!Number.isFinite(duration)||position<1)return;const progress=duration>0?Math.min(99.9,(position/duration)*100):0;try{if(completed)localStorage.removeItem(local);else localStorage.setItem(local,JSON.stringify({position_seconds:position,duration_seconds:duration,updated_at:new Date().toISOString()}))}catch{}
 const item={id,mediaType,title:title||'Untitled',posterPath:null,backdropPath:null,progress,season,episode,timeLeft:duration>position?Math.ceil((duration-position)/60):undefined,duration};
 if(completed){await markCompleted(item);return}
 addOrUpdate(item);const token=getAccessToken();if(!token)return;const now=Date.now();if(now-lastSave.current<3000)return;lastSave.current=now;try{await fetch('/api/progress',{method:'POST',headers:{'Content-Type':'application/json',...headers()},body:JSON.stringify({profileId:(localStorage.getItem('rabbitrip.activeProfile:'+((JSON.parse(localStorage.getItem('rabbitrip.supabase.session')||'{}')?.user?.id)||'guest'))||'default'),mediaType,id,season,episode,position,duration,title:title||null,completed:false,backdropPath:null,posterPath:null}),keepalive:true})}catch{}};
 const attach=()=>{if(cancelled)return;const v=getVideo();if(!v||videoRef.current===v)return;if(videoRef.current){/* old node replaced */}videoRef.current=v;const onMeta=()=>void restore(v);const onSeeking=()=>{wantedPlayRef.current=!v.paused;if(wantedPlayRef.current){try{v.pause()}catch{}}};const onSeeked=()=>{if(wantedPlayRef.current){void v.play().catch(()=>{})}wantedPlayRef.current=false};const onCanPlay=()=>{if(wantedPlayRef.current){void v.play().catch(()=>{})}};const onWaiting=()=>{if(!v.paused)wantedPlayRef.current=true};const onPlaying=()=>{wantedPlayRef.current=false};const onTime=()=>void save(false);const onEnded=()=>void save(true);v.addEventListener('loadedmetadata',onMeta);v.addEventListener('canplay',onCanPlay);v.addEventListener('seeking',onSeeking);v.addEventListener('seeked',onSeeked);v.addEventListener('waiting',onWaiting);v.addEventListener('playing',onPlaying);v.addEventListener('timeupdate',onTime);v.addEventListener('ended',onEnded);void restore(v);timer=setInterval(()=>void save(false),5000);
 return()=>{v.removeEventListener('loadedmetadata',onMeta);v.removeEventListener('canplay',onCanPlay);v.removeEventListener('seeking',onSeeking);v.removeEventListener('seeked',onSeeked);v.removeEventListener('waiting',onWaiting);v.removeEventListener('playing',onPlaying);v.removeEventListener('timeupdate',onTime);v.removeEventListener('ended',onEnded);if(timer)clearInterval(timer)};
 };
 const cleanup=()=>{if(timer)clearInterval(timer)};const first=attach();if(!first)timer=setInterval(()=>{if(!cancelled&&!videoRef.current){const c=attach();if(c)clearInterval(timer!)}},300);window.addEventListener('pagehide',()=>void save(false));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')void save(false)});
 return()=>{cancelled=true;cleanup();if(first)first()};
 },[addOrUpdate,id,markCompleted,mediaType,season,episode,title]);return null}

export default function BingrWatchWithDownloads(){const p=useParams<{mediaType:string;id:string;season?:string;episode?:string}>();const mediaType=p.mediaType==='tv'?'tv':'movie';const id=Number(p.id),season=p.season?Number(p.season):undefined,episode=p.episode?Number(p.episode):undefined;const[open,setOpen]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[downloads,setDownloads]=useState<DownloadOption[]>([]);
 useEffect(()=>{if(!open||!Number.isFinite(id))return;const c=new AbortController();const q=new URLSearchParams({mediaType,id:String(id)});if(mediaType==='tv'){if(p.season)q.set('season',p.season);if(p.episode)q.set('episode',p.episode)}setLoading(true);setError('');setDownloads([]);fetch(`/api/bingr/download?${q}`,{headers:{Accept:'application/json'},signal:c.signal}).then(r=>{if(!r.ok)throw new Error();return r.json() as Promise<DownloadResponse>}).then(d=>{const o=Array.isArray(d.downloads)?d.downloads.filter(x=>typeof x?.url==='string'&&x.url.trim()):[];setDownloads(o);if(!o.length)setError('No download options found for this episode.')}).catch(e=>{if(e?.name!=='AbortError')setError('Download options are unavailable right now.')}).finally(()=>setLoading(false));return()=>c.abort()},[open,id,mediaType,p.season,p.episode]);
 return<><BingrWatch/><RecoveryAndProgress mediaType={mediaType} id={id} season={season} episode={episode}/><button type="button" onClick={()=>setOpen(true)} className="fixed right-4 top-4 z-[430] flex items-center gap-2 rounded-full border border-white/10 bg-black/60 px-4 py-2.5 text-sm font-semibold text-white backdrop-blur-xl" aria-label="Download options"><Download className="h-4 w-4"/><span className="hidden sm:inline">Download</span></button>{open&&<div className="fixed inset-0 z-[500] flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm" role="dialog" aria-modal="true"><div className="w-full max-w-lg overflow-hidden rounded-2xl border border-white/10 bg-[#0d0d0f]"><div className="flex items-center justify-between border-b border-white/10 p-4"><h3 className="text-lg font-bold">Download Options</h3><button type="button" onClick={()=>setOpen(false)}><X className="h-5 w-5"/></button></div><div className="max-h-[60vh] overflow-y-auto p-4">{loading?<div className="flex min-h-32 items-center justify-center"><Loader2 className="h-6 w-6 animate-spin"/></div>:error?<div className="py-10 text-center text-sm text-white/50">{error}</div>:<div className="flex flex-col gap-3">{downloads.map((item,i)=>{const url=String(item.url||'').trim(),label=qualityLabel(item.quality),provider=item.server||item.source||'Download',size=item.size?.trim()||'Unknown Size';return<div key={`${url}-${i}`} className="flex items-center justify-between gap-3 rounded-xl border border-white/5 bg-white/5 p-3"><div className="min-w-0 flex-1"><div className="text-sm font-semibold">{label}</div><div className="mt-1 text-xs text-white/50">{provider} • {size}</div></div><button type="button" disabled={!url} onClick={()=>openDownload(url)} className="flex h-10 w-10 items-center justify-center rounded-full bg-white/10 disabled:opacity-40"><Download className="h-4 w-4"/></button></div>})}</div>}</div></div></div>}</>}
