import { useState } from 'react';
import { ChevronLeft, ChevronRight, Pencil, Plus, Settings, Trash2 } from 'lucide-react';
import { Link, useLocation } from 'wouter';
import { useProfiles, DEFAULT_AVATARS } from '@/hooks/useProfiles';
import { useContinueWatching } from '@/hooks/useContinueWatching';
import { useWatchlist } from '@/hooks/useWatchlist';
import { useAuth } from '@/hooks/useAuth';
import { Seo } from '@/components/Seo';

const TAGLINES = ['Bingr: Cheaper than therapy, twice as addictive.','Welcome back. Your queue missed you.','Netflix and Chill? More like Bingr and finger... wait.'];

type EditState = { id: string | null; isNew: boolean } | null;
const imageOf = (value?: string | null) => value || '/placeholder-poster.jpg';
const ProgressBar = ({ value }: { value: number }) => <div className="absolute inset-x-0 bottom-0 h-1 bg-white/20"><div className="h-full bg-white" style={{ width: `${Math.max(0, Math.min(100, value))}%` }} /></div>;

export default function Space() {
  const [, navigate] = useLocation();
  const { isLoggedIn } = useAuth();
  const { profiles, activeProfile, activeId, setActiveId, addProfile, updateProfile, deleteProfile, isHydrated } = useProfiles();
  const { items: continueItems, isLoading: continueLoading } = useContinueWatching();
  const { watchlist, isLoading: watchlistLoading } = useWatchlist(isLoggedIn);
  const [edit, setEdit] = useState<EditState>(null);
  const [draftName, setDraftName] = useState('');
  const [draftAvatar, setDraftAvatar] = useState(DEFAULT_AVATARS[0]);
  const [saving, setSaving] = useState(false);

  if (!isHydrated) return <div className="min-h-screen bg-[#07070b]" />;
  const tagline = TAGLINES[Math.abs((activeProfile?.name || 'RabbitRip').charCodeAt(0)) % TAGLINES.length];
  const avatars = draftAvatar && !DEFAULT_AVATARS.includes(draftAvatar) ? [draftAvatar, ...DEFAULT_AVATARS] : DEFAULT_AVATARS;
  const selectedIndex = Math.max(0, avatars.indexOf(draftAvatar));
  const prevIndex = (selectedIndex - 1 + avatars.length) % avatars.length;
  const nextIndex = (selectedIndex + 1) % avatars.length;

  const openEdit = (id: string) => { const p = profiles.find(x => x.id === id); if (!p) return; setEdit({ id, isNew: false }); setDraftName(p.name); setDraftAvatar(p.avatar); };
  const openAdd = () => { setEdit({ id: null, isNew: true }); setDraftName(''); setDraftAvatar(DEFAULT_AVATARS[0]); };
  const closeEdit = () => { if (saving) return; setEdit(null); setDraftName(''); setDraftAvatar(DEFAULT_AVATARS[0]); };
  const saveProfile = () => { const name = draftName.trim(); if (!name || saving) return; setSaving(true); try { if (edit?.isNew) addProfile(name, draftAvatar); else if (edit?.id) updateProfile(edit.id, { name, avatar: draftAvatar }); closeEdit(); } finally { setSaving(false); } };
  const removeProfile = () => { if (!edit?.id) return; const p = profiles.find(x => x.id === edit.id); if (!p || !window.confirm(`Delete ${p.name}?`)) return; deleteProfile(p.id); closeEdit(); };

  return <div className="min-h-screen bg-[#07070b] text-white pb-28" data-testid="page-space">
    <Seo title="My Space" />
    <main className="mx-auto w-full max-w-[1180px] px-5 pt-10 md:px-10 md:pt-16">
      <header className="mb-10 flex items-start justify-between gap-4"><div><h1 className="text-[34px] font-extrabold tracking-tight md:text-5xl">Hey, {activeProfile?.name || 'there'}</h1><p className="mt-1 text-sm font-medium text-white/45 md:text-base">{tagline}</p></div><div className="flex items-center gap-2"><button type="button" onClick={() => navigate('/settings')} className="flex h-14 w-14 items-center justify-center rounded-2xl border border-white/10 bg-white/[0.035] text-white/80 transition hover:bg-white/[0.07]" aria-label="Settings"><Settings className="h-5 w-5" /></button><button type="button" onClick={() => navigate('/home')} className="flex h-14 w-14 items-center justify-center rounded-2xl border border-white/10 bg-white/[0.035] text-white/80 transition hover:bg-white/[0.07]" aria-label="Home"><ChevronRight className="h-6 w-6" /></button></div></header>

      <section className="mb-12"><div className="mb-6 flex items-center justify-between"><h2 className="text-[26px] font-bold tracking-tight">Profiles</h2><button type="button" onClick={() => activeId && openEdit(activeId)} disabled={!activeId} className="inline-flex items-center gap-2 rounded-xl bg-white/[0.055] px-5 py-3 text-sm font-semibold text-white disabled:opacity-30"><Pencil className="h-4 w-4" /> Edit</button></div><div className="flex items-start gap-7 overflow-x-auto pb-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">
        {profiles.map(profile => { const selected = profile.id === activeId; return <button key={profile.id} type="button" onClick={() => setActiveId(profile.id)} className="group flex w-[105px] shrink-0 flex-col items-center gap-3 text-center outline-none md:w-[130px]"><div className={`relative h-[92px] w-[92px] overflow-hidden rounded-full border-2 transition md:h-[120px] md:w-[120px] ${selected ? 'border-white/60' : 'border-white/10 group-hover:border-white/30'}`}><img src={profile.avatar} alt={profile.name} className="h-full w-full object-cover" onError={e => { e.currentTarget.src = '/brand/logo.png'; }} />{selected && <span className="absolute bottom-0 right-0 flex h-8 w-8 items-center justify-center rounded-full border-2 border-[#07070b] bg-white text-black"><span className="text-sm font-black">✓</span></span>}</div><span className={`max-w-full truncate text-sm font-semibold ${selected ? 'text-white' : 'text-white/55 group-hover:text-white/80'}`}>{profile.name}</span></button>; })}
        <button type="button" onClick={openAdd} className="group flex w-[105px] shrink-0 flex-col items-center gap-3 md:w-[130px]"><span className="flex h-[92px] w-[92px] items-center justify-center rounded-full border-2 border-dashed border-white/15 bg-white/[0.02] transition group-hover:border-white/35 group-hover:bg-white/[0.05] md:h-[120px] md:w-[120px]"><Plus className="h-9 w-9 text-white/45 group-hover:text-white" /></span><span className="text-sm font-semibold text-white/45 group-hover:text-white/80">Add</span></button>
      </div></section>

      <section className="mb-12"><div className="mb-5"><h2 className="text-[25px] font-bold tracking-tight">Continue Watching</h2></div>{continueLoading && !continueItems.length ? <div className="h-40 rounded-2xl bg-white/[0.03] animate-pulse" /> : continueItems.length ? <div className="flex gap-4 overflow-x-auto pb-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{continueItems.slice(0,20).map(item => <Link key={`${item.mediaType}-${item.id}-${item.season||0}-${item.episode||0}`} href={item.mediaType === 'movie' ? `/watch/movie/${item.id}` : `/watch/tv/${item.id}/${item.season||1}/${item.episode||1}`} className="group w-[230px] shrink-0 md:w-[280px]"><div className="relative aspect-video overflow-hidden rounded-xl bg-white/5"><img src={imageOf(item.backdropPath || item.posterPath)} alt={item.title} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black/85 via-transparent to-transparent" /><div className="absolute bottom-3 left-3 flex h-9 w-9 items-center justify-center rounded-full bg-white text-black">▶</div><ProgressBar value={item.progress} /></div><h3 className="mt-2 truncate text-sm font-semibold">{item.mediaType === 'tv' && item.episode ? `S${item.season||1} E${item.episode} • ${item.title}` : item.title}</h3><p className="mt-1 text-xs text-white/40">{item.timeLeft ? `${item.timeLeft}m left` : `${Math.round(item.progress)}% watched`}</p></Link>)}</div> : <p className="rounded-2xl border border-white/[0.06] bg-white/[0.02] px-5 py-8 text-sm text-white/35">Nothing here yet. Start watching something and it will appear here.</p>}</section>

      <section><div className="mb-5"><h2 className="text-[25px] font-bold tracking-tight">Watchlist</h2></div>{watchlistLoading ? <div className="h-40 rounded-2xl bg-white/[0.03] animate-pulse" /> : watchlist.length ? <div className="flex gap-5 overflow-x-auto pb-3 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{watchlist.map(item => <Link key={`${item.mediaType}-${item.titleId}`} href={`/title/${item.mediaType}/${item.titleId}`} className="group w-[150px] shrink-0 md:w-[190px]"><div className="relative aspect-[2/3] overflow-hidden rounded-xl bg-white/5"><img src={imageOf(item.titleSnapshot?.posterPath)} alt={item.titleSnapshot?.title || 'Watchlist item'} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /></div><h3 className="mt-2 truncate text-sm font-semibold">{item.titleSnapshot?.title || 'Untitled'}</h3><p className="mt-1 text-xs text-white/40">{item.mediaType === 'tv' ? 'TV' : 'Movie'}</p></Link>)}</div> : <p className="rounded-2xl border border-white/[0.06] bg-white/[0.02] px-5 py-8 text-sm text-white/35">Your watchlist is empty.</p>}</section>
    </main>

    {edit && <div className="fixed inset-0 z-[100] bg-[#07070b] text-white" role="dialog" aria-modal="true"><div className="mx-auto flex min-h-screen w-full max-w-3xl flex-col px-5 py-5 md:px-10"><header className="relative flex items-center justify-center"><button type="button" onClick={closeEdit} className="absolute left-0 rounded-full p-2 text-white/75 hover:bg-white/10" aria-label="Close"><ChevronLeft className="h-7 w-7" /></button><h2 className="text-xl font-bold md:text-2xl">{edit.isNew ? 'Add Profile' : 'Edit Profile'}</h2></header><div className="flex flex-1 flex-col items-center justify-center pb-16"><div className="relative mb-12 flex w-full max-w-[620px] items-center justify-center"><button type="button" onClick={() => setDraftAvatar(avatars[prevIndex])} className="absolute left-0 z-20 flex h-14 w-14 items-center justify-center rounded-full bg-black/60 text-white/70 shadow-xl backdrop-blur-md md:left-6" aria-label="Previous avatar"><ChevronLeft className="h-7 w-7" /></button><div className="flex items-center justify-center gap-5 overflow-hidden px-20">{[prevIndex, selectedIndex, nextIndex].map((index,slot) => { const avatar=avatars[index]; const selected=slot===1; return <button key={`${avatar}-${slot}`} type="button" onClick={() => setDraftAvatar(avatar)} className={`shrink-0 overflow-hidden rounded-full transition duration-300 ${selected ? 'h-40 w-40 ring-2 ring-white ring-offset-4 ring-offset-[#07070b] md:h-52 md:w-52' : 'h-24 w-24 opacity-50 md:h-32 md:w-32'}`}><img src={avatar} alt="Avatar" className="h-full w-full object-cover" onError={e => { e.currentTarget.src='/brand/logo.png'; }} /></button>; })}</div><button type="button" onClick={() => setDraftAvatar(avatars[nextIndex])} className="absolute right-0 z-20 flex h-14 w-14 items-center justify-center rounded-full bg-black/60 text-white/70 shadow-xl backdrop-blur-md md:right-6" aria-label="Next avatar"><ChevronRight className="h-7 w-7" /></button></div><div className="w-full max-w-[640px]"><input autoFocus value={draftName} onChange={e => setDraftName(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') saveProfile(); }} placeholder="Profile name" className="h-14 w-full rounded-xl border border-white/15 bg-white/[0.025] px-5 text-base text-white outline-none focus:border-white/35" /><button type="button" disabled={!draftName.trim() || saving} onClick={saveProfile} className="mt-6 h-14 w-full rounded-xl bg-white text-base font-bold text-black disabled:opacity-40">{edit.isNew ? 'Save & Continue' : 'Save'}</button>{!edit.isNew && <button type="button" onClick={removeProfile} className="mx-auto mt-10 flex items-center gap-2 text-sm font-semibold text-red-400/80 hover:text-red-400"><Trash2 className="h-4 w-4" /> Delete profile</button>}</div></div></div></div>}
  </div>;
}
