import { useEffect, useMemo } from "react";
import { Check, ChevronRight, Pencil, Plus, Settings, Play } from "lucide-react";
import { Link } from "wouter";
import { useProfiles, DEFAULT_AVATARS } from "@/hooks/useProfiles";
import { useContinueWatching } from "@/hooks/useContinueWatching";
import { useMyWatchlist } from "@/hooks/useUserData";
import { useAuth } from "@/hooks/useAuth";
import { useAds } from "@/hooks/useAds";
import { Seo } from "@/components/Seo";

const imageOf = (value?: string | null, width = "w500") => value ? (value.startsWith("http") ? value : `https://image.tmdb.org/t/p/${width}${value}`) : "/placeholder-poster.jpg";

function Starfield() {
  return <div className="pointer-events-none absolute inset-x-0 top-0 z-0 h-[330px] overflow-hidden"><div className="absolute inset-0 bg-gradient-to-b from-[#141414] via-[#050505] to-black" /><div className="absolute inset-0 opacity-40" style={{ backgroundImage: "radial-gradient(circle at 20% 18%, rgba(255,255,255,.75) 0 1px, transparent 1.5px), radial-gradient(circle at 58% 24%, rgba(255,255,255,.55) 0 1px, transparent 1.5px), radial-gradient(circle at 91% 34%, rgba(255,255,255,.7) 0 1px, transparent 1.5px), radial-gradient(circle at 36% 40%, rgba(255,255,255,.4) 0 1px, transparent 1.5px), radial-gradient(circle at 74% 52%, rgba(255,255,255,.55) 0 1px, transparent 1.5px)" }} /><div className="absolute inset-0 bg-gradient-to-b from-transparent via-black/70 to-black" /></div>;
}

function ProfileAvatar({ src, name, selected, onClick }: { src: string; name: string; selected: boolean; onClick: () => void }) {
  return <button type="button" onClick={onClick} className="group flex flex-col items-center gap-3 outline-none"><span className="relative block h-[72px] w-[72px] overflow-visible md:h-[120px] md:w-[120px]"><span className={`block h-full w-full overflow-hidden rounded-full ring-2 transition-all duration-300 group-hover:ring-white/60 ${selected ? "ring-white/40" : "ring-transparent"}`}><img src={src} alt={name} className="h-full w-full object-cover transition-transform duration-300 group-hover:scale-105" onError={(e) => { e.currentTarget.src = DEFAULT_AVATARS[0]; }} /></span>{selected && <span className="absolute bottom-0 right-0 flex h-7 w-7 items-center justify-center rounded-full border-[3px] border-[#080808] bg-[#eef2f6] text-black shadow-lg md:h-9 md:w-9"><Check className="h-3.5 w-3.5 md:h-5 md:w-5" strokeWidth={2.5} /></span>}</span><span className="text-sm font-semibold text-white/80 transition-colors group-hover:text-white">{name}</span></button>;
}

function PosterTray({ title, items, loading }: { title: string; items: any[]; loading?: boolean }) {
  if (!loading && items.length === 0) return null;
  return <section className="group/row relative mb-8"><h2 className="mb-3 px-6 text-lg font-semibold text-white/90 md:px-12">{title}</h2><div className="relative"><div className="no-scrollbar flex gap-3 overflow-x-auto scroll-smooth px-6 py-4 md:px-12">{loading ? Array.from({ length: 4 }).map((_, i) => <div key={i} className="aspect-[2/3] w-[150px] shrink-0 animate-pulse rounded-lg bg-white/5 sm:w-[170px]" />) : items.map((item: any) => <Link key={`${item.mediaType}-${item.titleId}`} href={`/title/${item.mediaType}/${item.titleId}`} className="group/card w-[150px] shrink-0 text-left sm:w-[170px]"><div className="relative aspect-[2/3] overflow-hidden rounded-lg bg-white/5 ring-1 ring-white/5 transition-all duration-300 group-hover/card:-translate-y-1 group-hover/card:ring-white/20"><img alt={item.titleSnapshot?.title || ""} loading="lazy" className="h-full w-full object-cover transition-transform duration-500 group-hover/card:scale-105" src={imageOf(item.titleSnapshot?.posterPath)} /><div className="pointer-events-none absolute inset-x-0 bottom-0 h-1/3 bg-gradient-to-t from-black/65 to-transparent" /></div><div className="mt-2 truncate text-[14px] font-semibold tracking-tight text-white/90">{item.titleSnapshot?.title || ""}</div><div className="mt-1 text-[11px] font-medium text-white/45">{item.titleSnapshot?.mediaType === "tv" ? "Series" : "Movie"}</div></Link>)}</div></div></section>;
}

function ContinueTray({ items, loading, profileName }: { items: any[]; loading: boolean; profileName?: string }) {
  if (!loading && items.length === 0) return null;
  return <section className="group relative mb-8"><div className="mb-4 flex w-full items-center justify-between gap-3 px-6 text-lg font-semibold text-white/90 md:gap-4 md:px-12"><div className="flex items-center gap-4"><h2>Continue Watching{profileName ? ` for ${profileName}` : ""}</h2><button type="button" aria-label="Edit continue watching" className="flex h-7 w-7 items-center justify-center rounded-full bg-white/5 text-white/50 transition hover:bg-white/15 hover:text-white"><Pencil className="h-4 w-4" strokeWidth={1.5} /></button></div></div><div className="no-scrollbar flex gap-4 overflow-x-auto py-4 px-6 md:px-12">{loading ? Array.from({ length: 3 }).map((_, i) => <div key={i} className="aspect-video w-[220px] shrink-0 animate-pulse rounded-md bg-[#1a1c20] md:w-[260px] lg:w-[300px]" />) : items.map((item: any) => { const progress = Math.min(100, Math.max(0, Number(item.progress) || 0)); const href = item.mediaType === "tv" ? `/watch/tv/${item.id}/${item.season || 1}/${item.episode || 1}` : item.mediaType === "anime" ? `/watch/anime/${item.id}/${item.episode || 1}` : `/watch/movie/${item.id}`; return <Link key={`${item.mediaType}-${item.id}-${item.season || ""}-${item.episode || ""}`} href={href} className="group/card flex w-[220px] shrink-0 flex-col gap-2 outline-none transition md:w-[260px] lg:w-[300px]"><div className="relative aspect-video w-full overflow-hidden rounded-md bg-[#1a1c20]"><img src={imageOf(item.backdropPath || item.posterPath, "w780")} alt={item.title || ""} loading="lazy" className="h-full w-full object-cover transition-transform duration-500 group-hover/card:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent" /><span className="absolute bottom-2 left-2 flex h-7 w-7 items-center justify-center rounded-full bg-black/40 backdrop-blur-sm"><Play className="h-4 w-4 fill-white" /></span><span className="absolute bottom-0 left-0 right-0 h-[3px] bg-white/20"><span className="block h-full bg-[#1875e5]" style={{ width: `${progress}%` }} /></span></div><div className="px-0.5"><h3 className="truncate text-[14px] font-semibold leading-snug text-white/90 sm:text-[15px]">{item.mediaType === "tv" ? `S${item.season || 1} E${item.episode || 1}` : item.title || ""}</h3><div className="mt-0.5 text-[12px] font-medium text-white/50">{item.mediaType === "tv" ? item.title || "" : item.timeLeft ? `${item.timeLeft}m left` : "Movie"}</div></div></Link>; })}</div></section>;
}

export default function Space() {
  const { profile } = useAuth();
  const { showAds, setShowAds } = useAds();
  const { profiles, activeProfile, activeId, setActiveId, isHydrated } = useProfiles();
  const { items: continueItems, isLoading: continueLoading } = useContinueWatching();
  const { data: watchlist = [], isLoading: watchlistLoading } = useMyWatchlist(activeId);
  useEffect(() => { if (!activeId && profiles[0]) setActiveId(profiles[0].id); }, [activeId, profiles, setActiveId]);
  const greeting = useMemo(() => "Netflix and Chill? More like Bingr and finger... wait.", []);
  if (!isHydrated) return <div className="min-h-screen bg-black" />;
  return <div className="relative min-h-screen overflow-x-hidden bg-black font-sans text-white" data-testid="page-space"><Seo title="My Space" /><Starfield /><main className="relative z-10 pb-24 md:pb-10 md:pl-[80px] lg:pl-[100px]">
    <section className="px-6 pt-20 md:px-12 md:pt-24"><div className="flex flex-col gap-8 md:flex-row md:items-start md:justify-between"><div className="w-full md:w-[60%]"><Link href="/settings/subscription" className="group flex items-center"><h1 className="text-[25px] font-semibold leading-tight tracking-tight text-white/95 md:text-[30px]">{greeting}</h1><ChevronRight className="ml-2 h-6 w-6 shrink-0 text-white/55 transition group-hover:text-white" /></Link><p className="mt-4 text-base font-medium text-white/55">{profile?.email || ""}</p></div><div className="flex w-full flex-col items-end gap-4 md:w-auto"><Link href="/settings" className="flex items-center gap-2 rounded-lg bg-white/5 px-4 py-2.5 text-sm font-semibold text-white/90 transition hover:bg-white/10"><Settings className="h-5 w-5 text-white/70" />Help &amp; Settings</Link><div className="flex items-center gap-3"><span className="text-sm font-medium text-white/60">Show Ads</span><button type="button" aria-pressed={showAds} onClick={() => setShowAds(!showAds)} className={`relative h-5 w-10 shrink-0 rounded-full transition-colors ${showAds ? "bg-white" : "bg-white/20"}`}><span className={`absolute top-[2px] h-4 w-4 rounded-full bg-black transition-transform ${showAds ? "translate-x-[22px]" : "translate-x-0.5"}`} /></button></div></div></div></section>
    <section className="mb-12 mt-16 px-6 md:px-12"><div className="mb-6 flex items-center justify-between"><h2 className="text-2xl font-semibold tracking-tight text-white/90">Profiles</h2><Link href="/profiles?edit=1" className="flex items-center gap-2 rounded-lg bg-white/5 px-4 py-2 text-sm font-semibold text-white/90 transition hover:bg-white/10"><Pencil className="h-4 w-4 text-white/70" />Edit</Link></div><div className="flex flex-wrap items-start gap-5 md:gap-8">{profiles.map((item) => <ProfileAvatar key={item.id} src={item.avatar} name={item.name} selected={item.id === activeId} onClick={() => setActiveId(item.id)} />)}{profiles.length < 3 && <Link href="/profiles" className="group flex flex-col items-center gap-3 outline-none"><span className="flex h-[72px] w-[72px] items-center justify-center rounded-full border border-dashed border-white/25 bg-white/[0.02] transition group-hover:border-white/40 group-hover:bg-white/10 md:h-[120px] md:w-[120px]"><Plus className="h-6 w-6 text-white/60 md:h-8 md:w-8" /></span><span className="text-sm font-medium text-white/60">Add</span></Link>}</div></section>
    <div className="mb-4"><PosterTray title="Watchlist" items={watchlist as any[]} loading={watchlistLoading} /><ContinueTray items={continueItems as any[]} loading={continueLoading} profileName={activeProfile?.name} /></div>
  </main></div>;
}
